# This is a basic workflow to help you get started with Actions

name: CIG

# Controls when the workflow will run
on:
  schedule:
   - cron: "30 08 * * *"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Performs the task
        run: |
          pip3 install -r requirements.txt
          git clone https://${{secrets.GHT}}@github.com/lucifermoningstar007/code1
          cd code1;python3 test.py
